title: Plaincheck
copyright: Joel Ellis (c) 2019
url: http://localhost:4000
sass:
  sass_dir:           _sass
  style:              compressed

markdown: kramdown
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE", "HARDBREAKS", "LIBERAL_HTML_TAG", "STRIKETHROUGH_DOUBLE_TILDE"]
  extensions: ["strikethrough", "autolink", "table"]

kramdown:
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge
exclude: [node_modules, dist, .sass-cache, .cache, .vscode, .babel.config.js, postcss.config.js, package.json, package-lock.json, Gemfile, Gemfile.lock, bsabel.config.js, brocfile.js, babel.config.js, Plaincheck.gemspec]

collections:
  authors:
    output: true
  favicons:
    permalink: /:path/:name
  root_files:
    permalink: /:path/:name

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true